import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import Layout from "@/app/components/Shared/layout/Layout";
import { NextIntlClientProvider } from "next-intl";
import { storeSettingsSportsTheme } from "@/app/data/storeSettingsSportsTheme";
import "@/app/styles/layout.css";
import "@/app/styles/headings.css";
import "@/app/styles/paragraphs.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const colors = storeSettingsSportsTheme.theme || {
		primary: "#1E40AF",
		secondary: "#9333EA",
		background: "#F9FAFB",
		text: "#111827",
	};

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				style={{
					["--color-header"]: colors.header,
					["--color-footer"]: colors.footer,
					["--color-cardsBg"]: colors.cardsBg,
					["--color-secondary"]: colors.secondary,
					["--color-background"]: colors.background,
					["--color-text"]: colors.text,
				}}>
				<ToastContainer />
				<ReactQueryProvider>
					<NextIntlClientProvider>
						<Layout>{children}</Layout>
					</NextIntlClientProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
